#ifndef _DEFINES_H
#define _DEFINES_H

////TODO
//glutGet(GLUT_WINDOW_WIDTH)
//glutGet(GLUT_WINDOW_HEIGHT)
//#define GLUT_WINDOW_WIDTH 800
//#define GLUT_WIDNOW_HEIGHT 600
//#define GLUT_INIT_WINDOW_X	100
//#define GLUT_INIT_WINDOW_Y	100

#endif

